import { State } from "./global-state.slint";
import { LegendData } from "./legend-data.slint";
component LegendEntry {
    in-out property<LegendData> data;
    HorizontalLayout {
        width: 100%;
        HorizontalLayout {
            alignment: start;
            width: 80%;
            spacing: 2pt;
            Rectangle {
                width: 12pt;
                height: 12pt;
                background: data.color;
            }
            Text {
                text: data.class;
            }
        }
        Text {
            text: data.time;
        }
    }
}


export component Legend {
    in-out property<[LegendData]> legend-data <=> State.legend-data;
    VerticalLayout {
        width: 100%;
        height: 100%;
        alignment: start;
        spacing: 2pt;
        for data in legend-data : LegendEntry {
            data: data;
        }
    }
}

